### PR TITLE
Updating PagerDuty Dashboard

### PR DESCRIPTION
**Pull request by john-knowles**
Changes include:

- New PagerDuty Logo
- Tweaked dashboard layout
- New screenshots

### CODE REVIEW

**Comment by jellyash** [comment]
With the replacement of the images, would it not make more sense to just add new files with the same name, rather than replacing the images and also changing the tile config?

**Comment by john-knowles** [comment]
> With the replacement of the images, would it not make more sense to just add new files with the same name, rather than replacing the images and also changing the tile config? This would allow anyone who already has the dashboard to simply copy the new files to the images folder and everything just work, without needing to replace the dashboard, which they may have already customised.

Thanks @jellyash - I've updated the file name for the PagerDuty logo.

**Comment by jellyash** [comment]
I see that the dashboard IDs have changed. Is this intentional?

**Comment by john-knowles** [comment]
> I see that the dashboard IDs have changed. Is this intentional?

No it was not intentional, please can you correct it?

**Comment by john-knowles** [comment]
> I see that the dashboard IDs have changed. Is this intentional?

@jellyash I have put the previous IDs back into the JSONs.

**Review by Sameer-Mhaisekar — APPROVED** [review]

**Review by shawn149 — APPROVED** [review]

**Pull request merged**
